import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f8f4ee',
  '--slot4-page-text': '#4e6173',
  '--slot4-panel-bg': '#f3e3d0',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#71879b',
  '--slot4-soft-muted-text': '#8ea9bf',
  '--slot4-accent': '#81A6C6',
  '--slot4-accent-fill': '#81A6C6',
  '--slot4-accent-soft': '#AACDDC',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#6f7f8f',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#d9e8f1',
  '--slot4-cream': '#f3e3d0',
  '--slot4-warm': '#fffaf4',
  '--slot4-lavender': '#aacddc',
  '--slot4-gray': '#eef4f7',
  '--slot4-body-gradient': 'radial-gradient(circle at top left, rgba(170,205,220,0.42), transparent 28%), linear-gradient(180deg, #fffdf9 0%, #f3e3d0 100%)',
  '--editable-page-bg': '#f8f4ee',
  '--editable-page-text': '#4e6173',
  '--editable-container': '1520px',
  '--editable-border': '#d5e3eb',
  '--editable-nav-bg': '#81A6C6',
  '--editable-nav-text': '#ffffff',
  '--editable-nav-active': '#AACDDC',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#D2C4B4',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#81A6C6',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_16px_40px_rgba(24,49,69,0.08)]',
  shadowStrong: 'shadow-[0_24px_54px_rgba(24,49,69,0.16)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(15,23,42,0.02),rgba(15,23,42,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-12 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-10 lg:grid-cols-[0.95fr_1.05fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[170px] shrink-0 snap-start sm:w-[190px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-semibold leading-[1.02] tracking-[-0.04em] sm:text-5xl lg:text-[3.5rem]',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.03em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[1.4rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.4rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.75rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-2xl bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-extrabold uppercase tracking-[0.08em] text-[var(--slot4-on-accent)] transition duration-200 hover:-translate-y-0.5 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-2xl border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-extrabold uppercase tracking-[0.08em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-2xl ${editablePalette.accentBg} px-6 py-3 text-sm font-extrabold uppercase tracking-[0.08em] text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.25rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_18px_34px_rgba(24,49,69,0.14)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing and mobile polish.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
